let kvadrat='\u2588';
let probel='\u0020';
let str, str1;

let plo=kvadrat.repeat(55)+'\n'+
probel.repeat(1)+kvadrat.repeat(54)+'\n'+
probel.repeat(2)+kvadrat.repeat(53)+'\n'+
probel.repeat(3)+kvadrat.repeat(52)+'\n'+
probel.repeat(4)+kvadrat.repeat(51)+'\n'+
probel.repeat(5)+kvadrat.repeat(50)+'\n'+
probel.repeat(6)+kvadrat.repeat(49)+'\n'+
probel.repeat(7)+kvadrat.repeat(48)+'\n'+
probel.repeat(8)+kvadrat.repeat(47)+'\n'+
probel.repeat(9)+kvadrat.repeat(46)+'\n'+
probel.repeat(10)+kvadrat.repeat(45)+'\n'+
probel.repeat(11)+kvadrat.repeat(44)+'\n'+
probel.repeat(12)+kvadrat.repeat(43)+'\n'+
probel.repeat(13)+kvadrat.repeat(42)+'\n'+
probel.repeat(14)+kvadrat.repeat(41)+'\n'+
probel.repeat(15)+kvadrat.repeat(40)+'\n'+
probel.repeat(16)+kvadrat.repeat(39)+'\n'+
probel.repeat(17)+kvadrat.repeat(38)+'\n'+
probel.repeat(18)+kvadrat.repeat(37)+'\n'+
probel.repeat(19)+kvadrat.repeat(36)+'\n'+
probel.repeat(20)+kvadrat.repeat(35)+'\n'+
probel.repeat(21)+kvadrat.repeat(34)+'\n'+
probel.repeat(22)+kvadrat.repeat(33)+'\n'+
probel.repeat(23)+kvadrat.repeat(32)+'\n'+
probel.repeat(24)+kvadrat.repeat(31)+'\n'+
probel.repeat(25)+kvadrat.repeat(30)+'\n'+
probel.repeat(26)+kvadrat.repeat(29)+'\n'+
probel.repeat(27)+kvadrat.repeat(28)+'\n'+
probel.repeat(26)+kvadrat.repeat(29)+'\n'+
probel.repeat(25)+kvadrat.repeat(30)+'\n'+
probel.repeat(24)+kvadrat.repeat(31)+'\n'+
probel.repeat(23)+kvadrat.repeat(32)+'\n'+
probel.repeat(22)+kvadrat.repeat(33)+'\n'+
probel.repeat(21)+kvadrat.repeat(34)+'\n'+
probel.repeat(20)+kvadrat.repeat(35)+'\n'+
probel.repeat(19)+kvadrat.repeat(36)+'\n'+
probel.repeat(18)+kvadrat.repeat(37)+'\n'+
probel.repeat(17)+kvadrat.repeat(38)+'\n'+
probel.repeat(16)+kvadrat.repeat(39)+'\n'+
probel.repeat(15)+kvadrat.repeat(40)+'\n'+
probel.repeat(14)+kvadrat.repeat(41)+'\n'+
probel.repeat(13)+kvadrat.repeat(42)+'\n'+
probel.repeat(12)+kvadrat.repeat(43)+'\n'+
probel.repeat(11)+kvadrat.repeat(44)+'\n'+
probel.repeat(10)+kvadrat.repeat(45)+'\n'+
probel.repeat(9)+kvadrat.repeat(46)+'\n'+
probel.repeat(8)+kvadrat.repeat(47)+'\n'+
probel.repeat(7)+kvadrat.repeat(48)+'\n'+
probel.repeat(6)+kvadrat.repeat(49)+'\n'+
probel.repeat(5)+kvadrat.repeat(50)+'\n'+
probel.repeat(4)+kvadrat.repeat(51)+'\n'+
probel.repeat(3)+kvadrat.repeat(52)+'\n'+
probel.repeat(2)+kvadrat.repeat(53)+'\n'+
probel.repeat(1)+kvadrat.repeat(54)+'\n';
console.log(plo);